
export const MixpanelActions = {
    CLICKED:'Clicked',
    OPEN:'Open',
    ATTEMPTED:'Attempted',
    CLOSED: 'Closed'
};

export const MixpanelCategories = {
    LOGIN: 'Login',
    TOPIC: 'Topic',
    WORKSHEET: 'Worksheet',
    HOMEWORK: 'Homework',
    GAMES: 'Games',
    QUESTION: 'Question',
    HAMBURGER:'Hamburger',
    TITLE : 'Title',
    REWARDS: 'Rewards', 
    LEADERBOARD: 'Leaderboard',
    PREVIEW: 'Preview',
    LOGOUT: 'Logout',
    PROFILE : 'Profile',
    INACTIVESESSION: 'Inactivesession',
    HOME: 'Home',
    TRUSTEDDEVICE: 'TrustedDevice',
    CERTIFICATE: 'Certificate'
}

export const MixpanelEvents = {
    LOGIN_PAGE_OPEN: 'Login Page Open',
    INVALID_USER_NAME: 'Invalid User Name',
    INCORRECT_PASSWORD: 'Incorrect Password',
    VALIDATE_USERNAME: 'Next Login Button',
    EARNED_SPARKIES: 'Earned Sparkies',
    LOGIN: "Login Button",
    EP_COL_SPARKY: 'Expand/Collapse Sparkie',
    FORGOT_PASSWORD_OPEN : 'Forgot Password open',
    HOME_HAMBURGER: 'Hamburger Button',
    STARRED_QUESTION: 'Go To Starred Question',
    MESSAGES: 'Go To Messages',
    PROFILES: 'Go To Profiles',
    GO_TO_HOME_FOOTER_PROFILE : 'Home_profile footer',
    GO_TO_VIEW_SUBSCRIPTION : 'Go To View Subscription',
    TOPIC_PAGE_OPEN: 'Topic Page Open',
    SESSION_REPORT_LEARNING_MAP : 'Session report - learning map',
    WORKSHEET_PAGE_OPEN: 'Worksheet Page Open',
    HOMEWORK_PAGE_OPEN: 'Homework Page Open',
    GAMES_PAGE_OPEN: 'Games Page Open',
    PLAY_GAME : 'Play Game',
    SAVE_CHANGES : 'Save Profile Changes',
    CHANGE_PASSWORD : 'Go To Change Password',
    PASSWORD_RESET_USING_OTP : 'Password Reset using Otp',
    TOPIC_OPEN: 'Topic Open',
    RESET_ASK_TEACHER : 'Reset Ask Teacher',
    TOPIC_CONTINUE: 'Topic Continue',
    TOPIC_DONE: 'Topic Done',
    HOMEWORK_OPEN: 'Homework Open',
    HOMEWORK_SUBMIT : 'Homework Submit',
    HOMEWORK_CONTINUE: 'Homework Continue',
    HOMEWORK_VIEW_SESSION_REPORT : 'Homework view report session',
    HOMEWORK_SEE_REPORT : 'Homework See Report',
    HOMEWORK_DONE: 'Homework Done',
    TOPIC_NEXT_QUESTION : 'Tc Next Question',
    WORKSHEET_OPEN: 'Worksheet Open',
    WORKSHEET_SEE_REPORT : 'Worksheet see Report', 
    WORKSHEET_CONTINUE: 'Worksheet Continue',
    WORKSHEET_SUBMIT : 'Worksheet Submit',
    SESSION_REPORT_GO_TO_HOME:'Session report - go to home',
    WORKSHEET_DONE: 'Worksheet Done',
    QUESTION_ATTEMPTED: 'Question Attempted',
    GO_TO_REWARDS: 'Go To Rewards',
    GO_TO_LEADERBOARD: 'Go To Leaderboard',
    GO_TO_PREVIEW: 'Go To Preview',
    GO_TO_HELP : 'Go To Help',
    GO_TO_HOME : 'Go To Home',
    MENU_PROFILE_IMAGE : 'Menu Profile Image',
    SECTION_LEADERBOARD: 'Section Leaderboard',
    CITY_LEADERBOARD: 'City Leaderboard',
    WORLD_LEADERBOARD: 'World Leaderboard',
    BADGES_REWARDS: 'Badges Rewards',
    TITLES_REWARDS: 'Titles Rewards',
    CERTIFICATES_REWARDS: 'Certificates Rewards',
    LOGOUT_USER: 'Click Logout Button',
    INACTIVE_USER: 'Inactive Popup Open',
    TOPIC_START : 'Topic Start',
    HOW_I_DID: 'How I Did',
    GO_BACK_TO_HOME_FROM_TOPIC : 'Topic tab - go to home',
    GO_BACK_TO_TOPIC_TAB : 'Topic map - go to topic tab',
    REVISE: 'Revise',
    HIGHER_LEVEL: 'Higher Level',
    NOTIFICATIONS: 'Go To Notifications',
    SESSION_REPORT: 'Content Session Report',
    TOTAL_SPARKIE: 'Total Sparkie',
    CONCEPT_COMPLETION: 'Concept Completion',
    SUBJECT_SELECTION : 'Subject selection',
    TRUSTED_CHECKBOX: 'Trusted Checkbox',
    TRUSTED_POP_UP_YES: 'Trusted PopUp Confirm',
    TRUSTED_POP_UP_NO: 'Trusted PopUp Cancel',
    MARK_AS_TRUSTED: 'Mark As Trusted',
    REMOVE_TRUSTED_DEVICE: 'Remove Trusted Device',
}