import {widthPercentageToDP as wp} from 'react-native-responsive-screen';
import {COLORS} from '@constants';

export default {
  squareOrange: {
    borderRadius: wp('2'),
    borderWidth: wp('0.5'),
    borderColor: COLORS.white,
    backgroundColor: COLORS.orange,
    backgroundDarker: COLORS.white,
    backgroundPlaceholder: COLORS.white,
    textColor: COLORS.white,
    backgroundProgress: COLORS.orange,
    raiseLevel: 1,
    backgroundShadow: 'transparent',
  },
  hintBlue: {
    borderRadius: wp('2'),
    borderWidth: wp('0.5'),
    borderColor: COLORS.white,
    backgroundColor: COLORS.carouselDotStyle,
    backgroundDarker: COLORS.white,
    backgroundPlaceholder: COLORS.white,
    textColor: COLORS.white,
    backgroundProgress: COLORS.white,
    raiseLevel: 0,
    backgroundShadow: 'transparent',
  },
  primaryOrange: {
    borderRadius: 25,
    backgroundColor: COLORS.orange,
    backgroundDarker: COLORS.darkOrangeColor,
    backgroundPlaceholder: COLORS.orange,
    textColor: COLORS.white,
    backgroundProgress: COLORS.orange,
    backgroundShadow: 'transparent',
    raiseLevel: 1,
  },
  elevatedOrange: {
    borderRadius: 10,
    backgroundColor: COLORS.btnColor,
    backgroundDarker: COLORS.orangeBtnDarker,
    backgroundPlaceholder: COLORS.orange,
    textColor: COLORS.white,
    backgroundShadow: 'transparent',
    raiseLevel: 6,
  },
  elevatedBlue: {
    borderRadius: 10,
    backgroundColor: COLORS.parentBlue,
    backgroundDarker: COLORS.parentBlue,
    backgroundPlaceholder: COLORS.parentBlue,
    textColor: COLORS.white,
    backgroundProgress: COLORS.teacherBlue,
    raiseLevel: 6,
    backgroundShadow: 'transparent',
  },
  squareDisabledElevated: {
    borderRadius: 10,
    backgroundColor: COLORS.disabledGray,
    backgroundDarker: COLORS.pedagogyGray,
    backgroundPlaceholder: COLORS.disabledGray,
    textColor: COLORS.white,
    backgroundProgress: COLORS.disabledGray,
    raiseLevel: 6,
    backgroundShadow: 'transparent',
  },
  squareDisabled: {
    borderRadius: wp('2'),
    borderWidth: wp('0.5'),
    borderColor: COLORS.white,
    backgroundColor: COLORS.disabledGray,
    backgroundDarker: COLORS.white,
    backgroundPlaceholder: COLORS.white,
    textColor: COLORS.white,
    backgroundProgress: COLORS.white,
    raiseLevel: 0,
    backgroundShadow: 'transparent',
  },
  secondaryWhite: {
    borderRadius: 10,
    backgroundColor: COLORS.secondaryWhite,
    backgroundDarker: COLORS.secondaryWhiteDark,
    backgroundPlaceholder: COLORS.secondaryWhite,
    textColor: COLORS.orange,
    backgroundProgress: COLORS.orange,
    raiseLevel: 6,
    backgroundShadow: 'transparent',
  },
  disabledSecondaryWhite: {
    borderRadius: 10,
    backgroundColor: COLORS.disabledSecondaryWhite,
    backgroundDarker: '#BFBFBF',
    backgroundPlaceholder: COLORS.disabledSecondaryWhite,
    textColor: COLORS.orange,
    backgroundProgress: COLORS.orange,
    raiseLevel: 6,
    backgroundShadow: 'transparent',
  },
  disabledGray: {
    borderRadius: 25,
    backgroundColor: COLORS.disabledGray,
    backgroundDarker: COLORS.disabledGray,
    backgroundPlaceholder: COLORS.disabledGray,
    textColor: COLORS.white,
    backgroundProgress: COLORS.disabledGray,
    raiseLevel: 0,
    backgroundShadow: 'transparent',
  },
  teacherBlue: {
    borderRadius: 25,
    backgroundColor: COLORS.teacherBlue,
    backgroundDarker: COLORS.teacherBlue,
    backgroundPlaceholder: COLORS.teacherBlue,
    textColor: COLORS.white,
    backgroundProgress: COLORS.teacherBlue,
    raiseLevel: 1,
    backgroundShadow: 'transparent',
  },
  parentBlue: {
    borderRadius: 25,
    backgroundColor: COLORS.parentBlue,
    backgroundDarker: COLORS.parentBlue,
    backgroundPlaceholder: COLORS.parentBlue,
    textColor: COLORS.white,
    backgroundProgress: COLORS.parentBlue,
    raiseLevel: 1,
    backgroundShadow: 'transparent',
  },
  primaryWhite: {
    borderRadius: 25,
    backgroundColor: COLORS.white,
    // backgroundDarker: COLORS.red,
    // backgroundPlaceholder: COLORS.orange,
    textColor: COLORS.subtitleDarkBlue,
    // backgroundProgress: COLORS.orange,
    // raiseLevel: 1,
    borderColor: COLORS.disabledGray,
    borderWidth: 1,
    backgroundShadow: 'transparent',
  },
  primaryGreen: {
    borderRadius: 25,
    backgroundColor: COLORS.green,
    backgroundDarker: COLORS.green,
    backgroundPlaceholder: COLORS.green,
    textColor: COLORS.white,
    backgroundProgress: COLORS.green,
    raiseLevel: 0,
    backgroundShadow: 'transparent',
  }
};
