import { COLORS } from '../../constants/COLORS';

export default {
  primaryOrange: {
    borderRadius: 25,
    backgroundColor: COLORS.btnColor,
    backgroundDarker: COLORS.orangeBtnDarker,
    backgroundPlaceholder: COLORS.orange,
    textColor: COLORS.white,
    backgroundProgress: COLORS.orange,
    raiseLevel: 0,
  },
  primaryWhite: {
    borderRadius: 25,
    backgroundColor: COLORS.white,
    backgroundDarker: COLORS.white,
    backgroundPlaceholder: COLORS.white,
    textColor: COLORS.white,
    backgroundProgress: COLORS.white,
    raiseLevel: 0,
  },
  disabledGray: {
    borderRadius: 25,
    backgroundColor: COLORS.disabledGray,
    backgroundDarker: COLORS.disabledGray,
    backgroundPlaceholder: COLORS.disabledGray,
    textColor: COLORS.white,
    backgroundProgress: COLORS.disabledGray,
    raiseLevel: 0,
  },
  teacherBlue: {
    borderRadius: 25,
    backgroundColor: COLORS.teacherBlue,
    backgroundDarker: COLORS.teacherBlue,
    backgroundPlaceholder: COLORS.teacherBlue,
    textColor: COLORS.white,
    backgroundProgress: COLORS.teacherBlue,
    raiseLevel: 1,
  },
  parentBlue: {
    borderRadius: 25,
    backgroundColor: COLORS.parentBlue,
    backgroundDarker: COLORS.parentBlue,
    backgroundPlaceholder: COLORS.parentBlue,
    textColor: COLORS.white,
    backgroundProgress: COLORS.parentBlue,
    raiseLevel: 1,
  },
  secondaryWhite: {
    borderRadius: 10,
    backgroundColor: COLORS.secondaryWhite,
    backgroundDarker: COLORS.secondaryWhiteDark,
    backgroundPlaceholder: COLORS.secondaryWhite,
    textColor: COLORS.orange,
    backgroundProgress: COLORS.orange,
    raiseLevel: 6,
  },
  elevatedOrange: {
    borderRadius: 3,
    backgroundColor: COLORS.btnColor,
    backgroundDarker: COLORS.orangeBtnDarker,
    backgroundPlaceholder: COLORS.orange,
    textColor: COLORS.white,
    backgroundProgress: COLORS.orange,
    raiseLevel: 3,
  },
  lightPink: {
    borderRadius: 25,
    backgroundColor: COLORS.buttonPink,
    backgroundDarker: COLORS.buttonPink,
    backgroundPlaceholder: COLORS.buttonPink,
    textColor: COLORS.buttonPink,
    backgroundProgress: COLORS.buttonPink,
    raiseLevel: 0,
  },
  maroon: {
    borderWidth: 1,
    borderColor: COLORS.maroon,
    borderRadius: 25,
    backgroundColor: COLORS.white,
    backgroundDarker: COLORS.white,
    backgroundPlaceholder: COLORS.maroon,
    textColor: COLORS.maroon,
    backgroundProgress: COLORS.maroon,
    raiseLevel: 0,
  }
};
