import getDeviceDetails from './getDeviceDetails';
import {
  setAsValue,
  getAsValue,
  MultigetAsValue,
  multiRemoveValue,
  clearStorage,
} from './asyncStorage';
import formValidation from './formValidation';
import { navigate, navigateRef } from './NavigationService';
import {
  respHp,
  respWp,
  getHp,
  getWp,
  getStatusBarHeight,
  getAspectRation,
  toTitleCase,
  camelCaseToString,
  checkForAudio,
  hp,
  wp,
  notificationRedirection
} from './ViewUtils';
import {
  getFormatedDateTime,
  getAllDatesOfSpecificMonth,
  getCurrentMonthName,
  getParsedDate,
  getParsedTime,
  getBetweenDates,
  dateToString,
  getCurrentMonth,
  getCurrentYear,
  getFormatedDate,
  getTimeDiff,
  getMonthYear,
  notificationTimeDifference,
} from './DateUtils';

import {
  replaceInput,
  replaceInputWithAnswer,
  appVersionCompare,
  replaceString,
  replaceTwiceString,
  getParsedTimeDifference,
  slugify,
  getCircularReplacer,
  capitalize,
  validateUserResponseArrays,
  validateArrays,
  generateValidArray,
  createValidURL,
  convertFirstCharToCaptial,
  HandleTheMathJax,
  isHTML,
  unitsCheck,
  getProductName,
  getLanguageUrl,
  replaceAll,
  screenLogging,
  getImages,
  getSubString,
  isOnlineUser,
  ValidationMessage,
  deviceHeight,
  deviceWidth,
  deviceInfo,
  isTablet,
  GetCertificateHtmlTemplet,
  captureDeviceDetails,
  clearUserData,
  getAudioUrls,
  audioHtmlTemplet,
  USE_NATIVE_DRIVER
} from './Utils';
import onboardingLottie from './onboardingLottie';

import { timeDifference } from './DateUtils';

import { configurePushNotification } from './notification';
import PwdValidation from './PwdValidation';

import SimpleHtmlTemplate from './SimpleHtmlTemplate';
import ContentServiceHTMLTemplate from './ContentServiceHTMLTemplate';
import MathHTMLTemplate from './MathHTMLTemplate';
import MathContentServiceHTMLTemplate from './MathContentServiceHTMLTemplate';
import IframeMathHTMLTemplate from './IframeMathHTMLTemplate';
import IframeHTMLTemplate from './IframeHTMLTemplate';

export {
  checkForAudio,
  getAspectRation,
  getDeviceDetails,
  setAsValue,
  getAsValue,
  MultigetAsValue,
  multiRemoveValue,
  formValidation,
  respHp,
  respWp,
  getHp,
  getWp,
  getStatusBarHeight,
  navigateRef,
  navigate,
  getFormatedDateTime,
  getFormatedDate,
  getTimeDiff,
  replaceInput,
  replaceInputWithAnswer,
  replaceString,
  replaceTwiceString,
  getParsedTimeDifference,
  onboardingLottie,
  slugify,
  getCircularReplacer,
  capitalize,
  validateUserResponseArrays,
  validateArrays,
  generateValidArray,
  toTitleCase,
  getParsedDate,
  getParsedTime,
  getBetweenDates,
  dateToString,
  getCurrentMonth,
  getCurrentMonthName,
  getMonthYear,
  camelCaseToString,
  getAllDatesOfSpecificMonth,
  timeDifference,
  getCurrentYear,
  createValidURL,
  clearStorage,
  convertFirstCharToCaptial,
  hp,
  wp,
  notificationTimeDifference,
  configurePushNotification,
  PwdValidation,
  SimpleHtmlTemplate,
  ContentServiceHTMLTemplate,
  MathHTMLTemplate,
  MathContentServiceHTMLTemplate,
  HandleTheMathJax,
  IframeMathHTMLTemplate,
  IframeHTMLTemplate,
  isHTML,
  unitsCheck,
  getProductName,
  appVersionCompare,
  getLanguageUrl,
  replaceAll,
  screenLogging,
  getSubString,
  getImages,
  isOnlineUser,
  ValidationMessage,
  deviceHeight,
  deviceWidth,
  deviceInfo,
  notificationRedirection,
  isTablet,
  GetCertificateHtmlTemplet,
  captureDeviceDetails,
  clearUserData,
  getAudioUrls,
  audioHtmlTemplet,
  USE_NATIVE_DRIVER
};
